name: CI/CD Pipeline (Dev/Test/Prod)

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  deploy-dev:
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-Dev')
    runs-on: ubuntu-latest
    name: Deploy to Development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Dev Deployment
        run: echo "🚀 Deploying to Development Server for ${{ github.ref }}"

  deploy-test:
    if: startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-Test')
    runs-on: ubuntu-latest
    name: Deploy to Testing

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Test Deployment
        run: echo "🚀 Deploying to Testing Server for ${{ github.ref }}"

  deploy-prod:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    name: Deploy to Production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Production Deployment
        run: echo "🚀 Deploying to Production Server for tag ${{ github.event.release.tag_name }}"
